using System.Runtime.CompilerServices;

public static class ModuleInitializer
{
    [ModuleInitializer]
    public static void Init()
    {
        // Configure Verify to work with source generators
        VerifySourceGenerators.Initialize();

        // Configure scrubbers to clean up auto-generated comments
        VerifierSettings.ScrubLinesContaining("// <auto-generated");
        VerifierSettings.ScrubLinesContaining("// This code was generated");
        VerifierSettings.ScrubLinesContaining("// Changes to this file");
        VerifierSettings.ScrubLinesContaining("// </auto-generated");

        // Use source generator scrubbers
        VerifierSettings.AddScrubber(builder =>
        {
            // Remove timestamps and paths that might vary between runs
            builder.Replace(
                System.Environment.NewLine + System.Environment.NewLine,
                System.Environment.NewLine);
        });
    }
}
