using System.Text;

namespace ObdInsight.Core.Diagnostics;

/// <summary>
/// Generates markdown-formatted reports suitable for GitHub issues.
/// </summary>
public static class MarkdownReportGenerator
{
    /// <summary>
    /// Generates a complete markdown report from diagnostic data.
    /// </summary>
    public static string Generate(DiagnosticReport report)
    {
        var sb = new StringBuilder();

        // Header
        sb.AppendLine("# Vehicle/Adapter Support Request");
        sb.AppendLine();
        sb.AppendLine($"**Generated:** {report.GeneratedAt:yyyy-MM-dd HH:mm:ss} UTC");
        sb.AppendLine($"**Tool Version:** {report.ToolVersion}");
        sb.AppendLine();

        // User Vehicle Info
        AppendVehicleInfo(sb, report.UserVehicleInfo);

        // Summary
        AppendSummary(sb, report);

        // BLE Adapter Info
        if (report.BleAdapterInfo != null)
        {
            AppendBleAdapterInfo(sb, report.BleAdapterInfo);
        }

        // OBD Adapter Info
        if (report.ObdAdapterInfo != null)
        {
            AppendObdAdapterInfo(sb, report.ObdAdapterInfo);
        }

        // Vehicle ID
        if (report.VehicleId != null)
        {
            AppendVehicleId(sb, report.VehicleId);
        }

        // Supported PIDs
        if (report.SupportedPids != null)
        {
            AppendSupportedPids(sb, report.SupportedPids);
        }

        // PID Probe Results
        if (report.StandardPidResults.Count > 0)
        {
            AppendPidProbeResults(sb, "Standard PID Responses", report.StandardPidResults);
        }

        if (report.ExtendedPidResults.Count > 0)
        {
            AppendPidProbeResults(sb, "Extended/EV PID Responses", report.ExtendedPidResults);
        }

        // Errors
        if (report.Errors.Count > 0)
        {
            AppendErrors(sb, report.Errors);
        }

        // Collection Notes
        if (report.Notes.Count > 0)
        {
            AppendNotes(sb, report.Notes);
        }

        // Footer
        sb.AppendLine("---");
        sb.AppendLine();
        sb.AppendLine("*This report was generated by ObdInsight. Please attach this file to your GitHub issue.*");

        return sb.ToString();
    }

    private static void AppendVehicleInfo(StringBuilder sb, UserVehicleInfo info)
    {
        sb.AppendLine("## Vehicle Information (User Provided)");
        sb.AppendLine();
        sb.AppendLine("| Property | Value |");
        sb.AppendLine("|----------|-------|");
        sb.AppendLine($"| Year | {info.Year} |");
        sb.AppendLine($"| Make | {info.Make} |");
        sb.AppendLine($"| Model | {info.Model} |");

        if (!string.IsNullOrEmpty(info.Trim))
            sb.AppendLine($"| Trim | {info.Trim} |");
        if (!string.IsNullOrEmpty(info.EngineType))
            sb.AppendLine($"| Engine/Powertrain | {info.EngineType} |");
        if (!string.IsNullOrEmpty(info.TransmissionType))
            sb.AppendLine($"| Transmission | {info.TransmissionType} |");

        sb.AppendLine();

        if (!string.IsNullOrEmpty(info.AdditionalNotes))
        {
            sb.AppendLine("**Additional Notes:**");
            sb.AppendLine($"> {info.AdditionalNotes}");
            sb.AppendLine();
        }
    }

    private static void AppendSummary(StringBuilder sb, DiagnosticReport report)
    {
        sb.AppendLine("## Summary");
        sb.AppendLine();

        var checksTable = new List<(string Check, bool? Passed, string Details)>();

        // BLE connection
        checksTable.Add(("BLE Connection", report.BleAdapterInfo != null,
            report.BleAdapterInfo?.DeviceName ?? "Not connected"));

        // Adapter detection
        var adapterName = report.ObdAdapterInfo?.VersionResponse?.Trim();
        checksTable.Add(("Adapter Detection", !string.IsNullOrEmpty(adapterName),
            adapterName ?? "Unknown"));

        // VIN read
        var vin = report.VehicleId?.Vin;
        checksTable.Add(("VIN Read", !string.IsNullOrEmpty(vin),
            vin != null ? MaskVin(vin) : "Not available"));

        // PIDs discovered
        var pidCount = report.SupportedPids?.Mode01Pids.Count ?? 0;
        checksTable.Add(("PID Discovery", pidCount > 0,
            $"{pidCount} Mode 01 PIDs"));

        // Standard PIDs responded
        var respondedPids = report.StandardPidResults.Count(r => r.Success);
        checksTable.Add(("PID Responses", respondedPids > 0,
            $"{respondedPids}/{report.StandardPidResults.Count} successful"));

        // EV indicators
        var evIndicators = report.ExtendedPidResults.Count(r => r.Success);
        var isLikelyEv = evIndicators > 0 || report.SupportedPids?.Mode01Pids.Contains("012F") == false;
        checksTable.Add(("EV/Hybrid Indicators", isLikelyEv ? true : null,
            isLikelyEv ? $"{evIndicators} EV PIDs responded" : "Standard vehicle"));

        sb.AppendLine("| Check | Status | Details |");
        sb.AppendLine("|-------|--------|---------|");

        foreach (var (check, passed, details) in checksTable)
        {
            var status = passed switch
            {
                true => "?",
                false => "?",
                null => "??"
            };
            sb.AppendLine($"| {check} | {status} | {EscapeMarkdown(details)} |");
        }

        sb.AppendLine();
    }

    private static void AppendBleAdapterInfo(StringBuilder sb, BleAdapterInfo info)
    {
        sb.AppendLine("## BLE Adapter Information");
        sb.AppendLine();
        sb.AppendLine($"**Device Name:** `{info.DeviceName}`");
        sb.AppendLine($"**MAC Address:** `{info.MacAddress}`");

        if (info.Rssi.HasValue)
            sb.AppendLine($"**RSSI:** {info.Rssi} dBm");

        sb.AppendLine();

        if (info.Services.Count > 0)
        {
            sb.AppendLine("<details>");
            sb.AppendLine("<summary>GATT Services & Characteristics</summary>");
            sb.AppendLine();
            sb.AppendLine("```");

            foreach (var service in info.Services)
            {
                sb.AppendLine($"Service: {service.ServiceUuid}");
                foreach (var characteristic in service.Characteristics)
                {
                    var props = string.Join(", ", characteristic.Properties);
                    sb.AppendLine($"  ?? {characteristic.CharacteristicUuid} [{props}]");
                }
            }

            sb.AppendLine("```");
            sb.AppendLine();
            sb.AppendLine("</details>");
            sb.AppendLine();
        }
    }

    private static void AppendObdAdapterInfo(StringBuilder sb, ObdAdapterInfo info)
    {
        sb.AppendLine("## OBD Adapter Information");
        sb.AppendLine();

        sb.AppendLine("| Property | Value |");
        sb.AppendLine("|----------|-------|");

        if (!string.IsNullOrEmpty(info.VersionResponse))
            sb.AppendLine($"| Version (ATI) | `{EscapeMarkdown(info.VersionResponse.Trim())}` |");
        if (!string.IsNullOrEmpty(info.DeviceDescription))
            sb.AppendLine($"| Description (AT@1) | `{EscapeMarkdown(info.DeviceDescription.Trim())}` |");
        if (!string.IsNullOrEmpty(info.VoltageResponse))
            sb.AppendLine($"| Voltage (ATRV) | `{EscapeMarkdown(info.VoltageResponse.Trim())}` |");
        if (!string.IsNullOrEmpty(info.ProtocolDescription))
            sb.AppendLine($"| Protocol (ATDP) | `{EscapeMarkdown(info.ProtocolDescription.Trim())}` |");
        if (!string.IsNullOrEmpty(info.ProtocolNumber))
            sb.AppendLine($"| Protocol # (ATDPN) | `{EscapeMarkdown(info.ProtocolNumber.Trim())}` |");

        sb.AppendLine();

        if (info.RawAtResponses.Count > 0)
        {
            sb.AppendLine("<details>");
            sb.AppendLine("<summary>Raw AT Command Responses</summary>");
            sb.AppendLine();
            sb.AppendLine("```");

            foreach (var (cmd, response) in info.RawAtResponses)
            {
                var cleanResponse = response.Replace("\r", "\\r").Replace("\n", "\\n");
                sb.AppendLine($"{cmd}: {cleanResponse}");
            }

            sb.AppendLine("```");
            sb.AppendLine();
            sb.AppendLine("</details>");
            sb.AppendLine();
        }
    }

    private static void AppendVehicleId(StringBuilder sb, VehicleIdentification info)
    {
        sb.AppendLine("## Vehicle Identification (ECU)");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(info.Vin))
        {
            sb.AppendLine($"**VIN:** `{MaskVin(info.Vin)}` (last 6 masked for privacy)");
        }
        else
        {
            sb.AppendLine("**VIN:** Not available");
        }

        if (!string.IsNullOrEmpty(info.CalibrationId))
            sb.AppendLine($"**Calibration ID:** `{EscapeMarkdown(info.CalibrationId.Trim())}`");
        if (!string.IsNullOrEmpty(info.EcuName))
            sb.AppendLine($"**ECU Name:** `{EscapeMarkdown(info.EcuName.Trim())}`");

        sb.AppendLine();

        if (!string.IsNullOrEmpty(info.RawVinResponse))
        {
            sb.AppendLine("<details>");
            sb.AppendLine("<summary>Raw VIN Response</summary>");
            sb.AppendLine();
            sb.AppendLine("```");
            sb.AppendLine(info.RawVinResponse);
            sb.AppendLine("```");
            sb.AppendLine();
            sb.AppendLine("</details>");
            sb.AppendLine();
        }
    }

    private static void AppendSupportedPids(StringBuilder sb, SupportedPidsInfo info)
    {
        sb.AppendLine("## Supported PIDs");
        sb.AppendLine();

        sb.AppendLine($"**Mode 01 (Live Data):** {info.Mode01Pids.Count} PIDs");
        if (info.Mode01Pids.Count > 0)
        {
            sb.AppendLine();
            sb.AppendLine("```");
            sb.AppendLine(string.Join(", ", info.Mode01Pids));
            sb.AppendLine("```");
        }

        sb.AppendLine();
        sb.AppendLine($"**Mode 09 (Vehicle Info):** {info.Mode09Pids.Count} PIDs");
        if (info.Mode09Pids.Count > 0)
        {
            sb.AppendLine();
            sb.AppendLine("```");
            sb.AppendLine(string.Join(", ", info.Mode09Pids));
            sb.AppendLine("```");
        }

        sb.AppendLine();

        if (info.RawResponses.Count > 0)
        {
            sb.AppendLine("<details>");
            sb.AppendLine("<summary>Raw Supported PIDs Responses</summary>");
            sb.AppendLine();
            sb.AppendLine("```");

            foreach (var (query, response) in info.RawResponses)
            {
                sb.AppendLine($"{query}: {response}");
            }

            sb.AppendLine("```");
            sb.AppendLine();
            sb.AppendLine("</details>");
            sb.AppendLine();
        }
    }

    private static void AppendPidProbeResults(StringBuilder sb, string title, IReadOnlyList<PidProbeResult> results)
    {
        sb.AppendLine($"## {title}");
        sb.AppendLine();

        // Show successful responses in main table
        var successful = results.Where(r => r.Success).ToList();
        var failed = results.Where(r => !r.Success).ToList();

        if (successful.Count > 0)
        {
            sb.AppendLine("### Successful Responses");
            sb.AppendLine();
            sb.AppendLine("| PID | Description | Response | Time |");
            sb.AppendLine("|-----|-------------|----------|------|");

            foreach (var result in successful)
            {
                var response = result.RawResponse ?? "";
                if (response.Length > 50)
                    response = response[..47] + "...";

                sb.AppendLine($"| `{result.Command}` | {result.Description} | `{EscapeMarkdown(response)}` | {result.ResponseTime.TotalMilliseconds:F0}ms |");
            }

            sb.AppendLine();
        }

        // Show raw data in collapsible section
        sb.AppendLine("<details>");
        sb.AppendLine("<summary>All PID Probe Data (Raw)</summary>");
        sb.AppendLine();
        sb.AppendLine("```");

        foreach (var result in results)
        {
            var status = result.Success ? "OK" : "FAIL";
            var response = result.RawResponse?.Replace("\r", "\\r").Replace("\n", "\\n") ?? result.Error ?? "";
            if (response.Length > 50)
                response = response[..47] + "...";
            sb.AppendLine($"[{status}] {result.Command} ({result.Description}): {response} [{result.ResponseTime.TotalMilliseconds:F0}ms]");
        }

        sb.AppendLine("```");
        sb.AppendLine();
        sb.AppendLine("</details>");
        sb.AppendLine();

        if (failed.Count > 0)
        {
            sb.AppendLine($"*{failed.Count} PIDs did not respond or returned errors*");
            sb.AppendLine();
        }
    }

    private static void AppendErrors(StringBuilder sb, IReadOnlyList<DiagnosticError> errors)
    {
        sb.AppendLine("## Errors Encountered");
        sb.AppendLine();

        foreach (var error in errors)
        {
            sb.AppendLine($"- **{error.Phase}:** {error.Message}");
            if (!string.IsNullOrEmpty(error.Details))
            {
                sb.AppendLine("  ```");
                sb.AppendLine($"  {error.Details}");
                sb.AppendLine("  ```");
            }
        }

        sb.AppendLine();
    }

    private static void AppendNotes(StringBuilder sb, IReadOnlyList<string> notes)
    {
        sb.AppendLine("## Collection Notes");
        sb.AppendLine();

        foreach (var note in notes)
        {
            sb.AppendLine($"- {note}");
        }

        sb.AppendLine();
    }

    /// <summary>
    /// Masks the last 6 characters of a VIN for privacy
    /// </summary>
    public static string MaskVin(string vin)
    {
        if (vin.Length <= 6)
            return new string('*', vin.Length);

        return vin[..^6] + "******";
    }

    /// <summary>
    /// Escapes special markdown characters
    /// </summary>
    private static string EscapeMarkdown(string text)
    {
        return text
            .Replace("|", "\\|")
            .Replace("`", "\\`")
            .Replace("\r", "")
            .Replace("\n", " ");
    }
}
