using System.Text;

namespace ObdInsight.Core.Diagnostics;

/// <summary>
/// Generates markdown-formatted reports suitable for GitHub issues.
/// </summary>
public static class MarkdownReportGenerator
{
    /// <summary>
    /// Generates a complete markdown report from diagnostic data.
    /// </summary>
    public static string Generate(DiagnosticReport report)
    {
        var sb = new StringBuilder();

        // Header
        sb.AppendLine("# Vehicle/Adapter Support Request");
        sb.AppendLine();
        sb.AppendLine($"**Generated:** {report.GeneratedAt:yyyy-MM-dd HH:mm:ss} UTC");
        sb.AppendLine($"**Tool Version:** {report.ToolVersion}");
        sb.AppendLine();

        // User Vehicle Info
        AppendVehicleInfo(sb, report.UserVehicleInfo);

        // Summary
        AppendSummary(sb, report);

        // Diagnostic Recommendations (NEW)
        AppendRecommendations(sb, report);

        // BLE Adapter Info
        if (report.BleAdapterInfo != null)
        {
            AppendBleAdapterInfo(sb, report.BleAdapterInfo);
        }

        // OBD Adapter Info
        if (report.ObdAdapterInfo != null)
        {
            AppendObdAdapterInfo(sb, report.ObdAdapterInfo);
        }

        // Protocol Probe Results (NEW)
        if (report.ProtocolProbeResults.Count > 0)
        {
            AppendProtocolProbeResults(sb, report.ProtocolProbeResults);
        }

        // Vehicle ID
        if (report.VehicleId != null)
        {
            AppendVehicleId(sb, report.VehicleId);
        }

        // Supported PIDs
        if (report.SupportedPids != null)
        {
            AppendSupportedPids(sb, report.SupportedPids);
        }

        // PID Probe Results
        if (report.StandardPidResults.Count > 0)
        {
            AppendPidProbeResults(sb, "Standard PID Responses", report.StandardPidResults);
        }

        if (report.ExtendedPidResults.Count > 0)
        {
            AppendPidProbeResults(sb, "Extended/EV PID Responses", report.ExtendedPidResults);
        }

        // CAN Probe Results (NEW)
        if (report.CanProbeResults.Count > 0)
        {
            AppendCanProbeResults(sb, report.CanProbeResults);
        }

        // Errors
        if (report.Errors.Count > 0)
        {
            AppendErrors(sb, report.Errors);
        }

        // Collection Notes
        if (report.Notes.Count > 0)
        {
            AppendNotes(sb, report.Notes);
        }

        // Footer
        sb.AppendLine("---");
        sb.AppendLine();
        sb.AppendLine("*This report was generated by ObdInsight. Please attach this file to your GitHub issue.*");

        return sb.ToString();
    }

    /// <summary>
    /// Masks the last 6 characters of a VIN for privacy
    /// </summary>
    public static string MaskVin(string vin)
    {
        if (vin.Length <= 6)
            return new string('*', vin.Length);

        return vin[..^6] + "******";
    }

    private static void AppendBleAdapterInfo(StringBuilder sb, BleAdapterInfo info)
    {
        sb.AppendLine("## BLE Adapter Information");
        sb.AppendLine();
        sb.AppendLine($"**Device Name:** `{info.DeviceName}`");
        sb.AppendLine($"**MAC Address:** `{info.MacAddress}`");

        if (info.Rssi.HasValue)
            sb.AppendLine($"**RSSI:** {info.Rssi} dBm");

        sb.AppendLine();

        if (info.Services.Count > 0)
        {
            sb.AppendLine("<details>");
            sb.AppendLine("<summary>GATT Services & Characteristics</summary>");
            sb.AppendLine();
            sb.AppendLine("```");

            foreach (var service in info.Services)
            {
                sb.AppendLine($"Service: {service.ServiceUuid}");
                foreach (var characteristic in service.Characteristics)
                {
                    var props = string.Join(", ", characteristic.Properties);
                    sb.AppendLine($"  ?? {characteristic.CharacteristicUuid} [{props}]");
                }
            }

            sb.AppendLine("```");
            sb.AppendLine();
            sb.AppendLine("</details>");
            sb.AppendLine();
        }
    }

    private static void AppendCanProbeResults(StringBuilder sb, IReadOnlyList<CanProbeResult> results)
    {
        sb.AppendLine("## EV CAN Address Probes");
        sb.AppendLine();

        var dataResults = results.Where(r => !r.Command.StartsWith("ATSH")).ToList();
        var successful = dataResults.Where(r => r.Success).ToList();

        if (successful.Count > 0)
        {
            sb.AppendLine("### Successful CAN Responses");
            sb.AppendLine();
            sb.AppendLine("| Header | Command | Description | Response | Time |");
            sb.AppendLine("|--------|---------|-------------|----------|------|");

            foreach (var result in successful)
            {
                var response = TruncateForTable(result.RawResponse);
                sb.AppendLine($"| `{result.Header ?? "default"}` | `{result.Command}` | {result.Description} | `{EscapeMarkdown(response)}` | {result.ResponseTime.TotalMilliseconds:F0}ms |");
            }

            sb.AppendLine();
        }
        else
        {
            sb.AppendLine("*No EV-specific CAN addresses responded. Vehicle may require different addressing.*");
            sb.AppendLine();
        }

        // Show all probes
        sb.AppendLine("<details>");
        sb.AppendLine("<summary>All CAN Probe Data</summary>");
        sb.AppendLine();
        sb.AppendLine("```");

        string? currentHeader = null;
        foreach (var result in results)
        {
            if (result.Command.StartsWith("ATSH"))
            {
                currentHeader = result.Command.Substring(4);
                sb.AppendLine($"--- Header: {currentHeader} ---");
            }
            else
            {
                var status = result.Success ? "OK" : "NO DATA";
                var response = result.RawResponse?.Replace("\r", "\\r").Replace("\n", "\\n") ?? "";
                if (response.Length > 60)
                    response = response[..57] + "...";
                sb.AppendLine($"[{status}] {result.Command}: {response} [{result.ResponseTime.TotalMilliseconds:F0}ms]");
            }
        }

        sb.AppendLine("```");
        sb.AppendLine();
        sb.AppendLine("</details>");
        sb.AppendLine();
    }

    private static void AppendErrors(StringBuilder sb, IReadOnlyList<DiagnosticError> errors)
    {
        sb.AppendLine("## Errors Encountered");
        sb.AppendLine();

        foreach (var error in errors)
        {
            sb.AppendLine($"- **{error.Phase}:** {error.Message}");
            if (!string.IsNullOrEmpty(error.Details))
            {
                sb.AppendLine("  ```");
                sb.AppendLine($"  {error.Details}");
                sb.AppendLine("  ```");
            }
        }

        sb.AppendLine();
    }

    private static void AppendNotes(StringBuilder sb, IReadOnlyList<string> notes)
    {
        sb.AppendLine("## Collection Notes");
        sb.AppendLine();

        foreach (var note in notes)
        {
            sb.AppendLine($"- {note}");
        }

        sb.AppendLine();
    }

    private static void AppendObdAdapterInfo(StringBuilder sb, ObdAdapterInfo info)
    {
        sb.AppendLine("## OBD Adapter Information");
        sb.AppendLine();

        sb.AppendLine("| Property | Value |");
        sb.AppendLine("|----------|-------|");

        if (!string.IsNullOrEmpty(info.VersionResponse))
            sb.AppendLine($"| Version (ATI) | `{EscapeMarkdown(info.VersionResponse.Trim())}` |");
        if (!string.IsNullOrEmpty(info.DeviceDescription))
            sb.AppendLine($"| Description (AT@1) | `{EscapeMarkdown(info.DeviceDescription.Trim())}` |");
        if (!string.IsNullOrEmpty(info.VoltageResponse))
            sb.AppendLine($"| Voltage (ATRV) | `{EscapeMarkdown(info.VoltageResponse.Trim())}` |");
        if (!string.IsNullOrEmpty(info.ProtocolDescription))
            sb.AppendLine($"| Protocol (ATDP) | `{EscapeMarkdown(info.ProtocolDescription.Trim())}` |");
        if (!string.IsNullOrEmpty(info.ProtocolNumber))
            sb.AppendLine($"| Protocol # (ATDPN) | `{EscapeMarkdown(info.ProtocolNumber.Trim())}` |");

        sb.AppendLine();

        if (info.RawAtResponses.Count > 0)
        {
            sb.AppendLine("<details>");
            sb.AppendLine("<summary>Raw AT Command Responses</summary>");
            sb.AppendLine();
            sb.AppendLine("```");

            foreach (var (cmd, response) in info.RawAtResponses)
            {
                var cleanResponse = response.Replace("\r", "\\r").Replace("\n", "\\n");
                sb.AppendLine($"{cmd}: {cleanResponse}");
            }

            sb.AppendLine("```");
            sb.AppendLine();
            sb.AppendLine("</details>");
            sb.AppendLine();
        }
    }

    private static void AppendPidProbeResults(StringBuilder sb, string title, IReadOnlyList<PidProbeResult> results)
    {
        sb.AppendLine($"## {title}");
        sb.AppendLine();

        // Show successful responses in main table
        var successful = results.Where(r => r.Success).ToList();
        var failed = results.Where(r => !r.Success).ToList();

        if (successful.Count > 0)
        {
            sb.AppendLine("### Successful Responses");
            sb.AppendLine();
            sb.AppendLine("| PID | Description | Response | Time |");
            sb.AppendLine("|-----|-------------|----------|------|");

            foreach (var result in successful)
            {
                var response = TruncateForTable(result.RawResponse);
                sb.AppendLine($"| `{result.Command}` | {result.Description} | `{EscapeMarkdown(response)}` | {result.ResponseTime.TotalMilliseconds:F0}ms |");
            }

            sb.AppendLine();
        }
        else
        {
            sb.AppendLine("*No PIDs in this category responded with data.*");
            sb.AppendLine();
        }

        // Show raw data in collapsible section
        sb.AppendLine("<details>");
        sb.AppendLine("<summary>All PID Probe Data (Raw)</summary>");
        sb.AppendLine();
        sb.AppendLine("```");

        foreach (var result in results)
        {
            var status = result.Success ? "OK" : "FAIL";
            var response = result.RawResponse?.Replace("\r", "\\r").Replace("\n", "\\n") ?? result.Error ?? "";
            if (response.Length > 50)
                response = response[..47] + "...";
            sb.AppendLine($"[{status}] {result.Command} ({result.Description}): {response} [{result.ResponseTime.TotalMilliseconds:F0}ms]");
        }

        sb.AppendLine("```");
        sb.AppendLine();
        sb.AppendLine("</details>");
        sb.AppendLine();

        if (failed.Count > 0)
        {
            sb.AppendLine($"*{failed.Count} PIDs did not respond or returned errors*");
            sb.AppendLine();
        }
    }

    private static void AppendProtocolProbeResults(StringBuilder sb, IReadOnlyList<ProtocolProbeResult> results)
    {
        sb.AppendLine("## Protocol Probe Results");
        sb.AppendLine();

        var working = results.Where(r => r.GotResponse).ToList();
        var notWorking = results.Where(r => !r.GotResponse && r.SetSuccess).ToList();

        if (working.Count > 0)
        {
            sb.AppendLine("### Working Protocols");
            sb.AppendLine();
            sb.AppendLine("| Protocol | Command | Response Time | Sample Response |");
            sb.AppendLine("|----------|---------|---------------|-----------------|");

            foreach (var result in working)
            {
                var response = TruncateForTable(result.TestResponse);
                sb.AppendLine($"| {result.Description} | `{result.ProtocolCommand}` | {result.ResponseTime.TotalMilliseconds:F0}ms | `{EscapeMarkdown(response)}` |");
            }

            sb.AppendLine();
        }
        else
        {
            sb.AppendLine("**No standard OBD-II protocols responded with data.**");
            sb.AppendLine();
        }

        if (notWorking.Count > 0)
        {
            sb.AppendLine("<details>");
            sb.AppendLine("<summary>Protocols Tested (No Response)</summary>");
            sb.AppendLine();
            sb.AppendLine("```");

            foreach (var result in notWorking)
            {
                var response = result.TestResponse?.Replace("\r", "\\r").Replace("\n", "\\n") ?? "NO DATA";
                sb.AppendLine($"{result.ProtocolCommand} ({result.Description}): {response}");
            }

            sb.AppendLine("```");
            sb.AppendLine();
            sb.AppendLine("</details>");
            sb.AppendLine();
        }
    }

    private static void AppendRecommendations(StringBuilder sb, DiagnosticReport report)
    {
        sb.AppendLine("## Diagnostic Analysis");
        sb.AppendLine();

        var recommendations = new List<string>();
        var findings = new List<string>();

        // Analyze what worked and what didn't
        var workingProtocols = report.ProtocolProbeResults.Where(p => p.GotResponse).ToList();
        var standardPidsWorked = report.StandardPidResults.Count(r => r.Success);
        var extendedPidsWorked = report.ExtendedPidResults.Count(r => r.Success);
        var canProbesWorked = report.CanProbeResults.Count(r => r.Success && !r.Command.StartsWith("ATSH"));
        var isEv = report.UserVehicleInfo.EngineType?.Contains("Electric") == true ||
                   report.UserVehicleInfo.EngineType?.Contains("BEV") == true;

        // Findings
        if (workingProtocols.Count > 0)
        {
            var protocols = string.Join(", ", workingProtocols.Select(p => p.Description));
            findings.Add($"**Working protocols:** {protocols}");
        }
        else
        {
            findings.Add("**No standard OBD-II protocols responded** - Vehicle may use proprietary protocol");
        }

        if (standardPidsWorked == 0 && isEv)
        {
            findings.Add("**No standard PIDs responded** - Expected for pure EVs which often don't implement OBD-II Mode 01");
        }

        if (report.VehicleId?.Vin == null)
        {
            findings.Add("**VIN not available** - Vehicle doesn't expose VIN via standard OBD-II Mode 09");
        }

        // Recommendations based on vehicle type
        if (isEv)
        {
            recommendations.Add("This is an **Electric Vehicle** which typically requires manufacturer-specific protocols");

            if (report.UserVehicleInfo.Make.Equals("Nissan", StringComparison.OrdinalIgnoreCase))
            {
                recommendations.Add("**Nissan Leaf/EV:** Try using CAN header 0x79B for battery data (ATSH79B then 2101-2104)");
                recommendations.Add("The Leaf uses ISO 15765-4 CAN but with non-standard addressing");
            }
            else if (report.UserVehicleInfo.Make.Equals("Tesla", StringComparison.OrdinalIgnoreCase))
            {
                recommendations.Add("**Tesla:** Uses proprietary CAN messages - standard OBD-II is very limited");
            }
            else if (report.UserVehicleInfo.Make.Equals("Chevrolet", StringComparison.OrdinalIgnoreCase) ||
                     report.UserVehicleInfo.Make.Equals("GM", StringComparison.OrdinalIgnoreCase))
            {
                recommendations.Add("**GM/Chevrolet EV:** Try Mode 22 PIDs (220101, 220102, 220105) for battery data");
            }
            else if (report.UserVehicleInfo.Make.Equals("Hyundai", StringComparison.OrdinalIgnoreCase) ||
                     report.UserVehicleInfo.Make.Equals("Kia", StringComparison.OrdinalIgnoreCase))
            {
                recommendations.Add("**Hyundai/Kia EV:** Try Mode 21 PIDs (2101-2105) and Mode 22 PIDs for battery data");
            }
            else
            {
                recommendations.Add("**Unknown EV:** Additional research needed for this vehicle's proprietary protocol");
            }

            if (canProbesWorked > 0)
            {
                recommendations.Add("? **Some EV CAN addresses responded** - this data can be used to develop a driver");
            }
        }

        if (standardPidsWorked > 0)
        {
            recommendations.Add($"? **Standard OBD-II support detected** - {standardPidsWorked} PIDs can be used");
        }

        // Output findings
        if (findings.Count > 0)
        {
            sb.AppendLine("### Findings");
            sb.AppendLine();
            foreach (var finding in findings)
            {
                sb.AppendLine($"- {finding}");
            }
            sb.AppendLine();
        }

        // Output recommendations
        if (recommendations.Count > 0)
        {
            sb.AppendLine("### Recommendations");
            sb.AppendLine();
            foreach (var rec in recommendations)
            {
                sb.AppendLine($"- {rec}");
            }
            sb.AppendLine();
        }

        // What to include in issue
        sb.AppendLine("### For GitHub Issue");
        sb.AppendLine();
        sb.AppendLine("When submitting this report, please include:");
        sb.AppendLine("1. Any additional observations about how your vehicle behaves");
        sb.AppendLine("2. Whether any aftermarket apps (LeafSpy, Torque, etc.) work with your vehicle");
        sb.AppendLine("3. What data you're most interested in (battery %, range, charging status, etc.)");
        sb.AppendLine();
    }

    private static void AppendSummary(StringBuilder sb, DiagnosticReport report)
    {
        sb.AppendLine("## Summary");
        sb.AppendLine();

        var checksTable = new List<(string Check, bool? Passed, string Details)>();

        // BLE connection
        checksTable.Add(("BLE Connection", report.BleAdapterInfo != null,
            report.BleAdapterInfo?.DeviceName ?? "Not connected"));

        // Adapter detection
        var adapterName = report.ObdAdapterInfo?.VersionResponse?.Trim();
        checksTable.Add(("Adapter Detection", !string.IsNullOrEmpty(adapterName),
            adapterName ?? "Unknown"));

        // Protocol probe
        var workingProtocols = report.ProtocolProbeResults.Count(p => p.GotResponse);
        checksTable.Add(("Working Protocols", workingProtocols > 0,
            workingProtocols > 0 ? $"{workingProtocols} protocol(s) responded" : "No protocols responded"));

        // VIN read
        var vin = report.VehicleId?.Vin;
        checksTable.Add(("VIN Read", !string.IsNullOrEmpty(vin),
            vin != null ? MaskVin(vin) : "Not available"));

        // PIDs discovered
        var pidCount = report.SupportedPids?.Mode01Pids.Count ?? 0;
        checksTable.Add(("PID Discovery", pidCount > 0,
            $"{pidCount} Mode 01 PIDs"));

        // Standard PIDs responded
        var respondedPids = report.StandardPidResults.Count(r => r.Success);
        checksTable.Add(("Standard PID Responses", respondedPids > 0,
            $"{respondedPids}/{report.StandardPidResults.Count} successful"));

        // Extended PIDs responded
        var extendedResponded = report.ExtendedPidResults.Count(r => r.Success);
        checksTable.Add(("Extended PID Responses", extendedResponded > 0,
            $"{extendedResponded}/{report.ExtendedPidResults.Count} successful"));

        // CAN probe results
        var canResponded = report.CanProbeResults.Count(r => r.Success && !r.Command.StartsWith("ATSH"));
        if (report.CanProbeResults.Count > 0)
        {
            checksTable.Add(("EV CAN Responses", canResponded > 0,
                $"{canResponded} CAN address(es) responded"));
        }

        // EV indicators
        var isLikelyEv = report.UserVehicleInfo.EngineType?.Contains("Electric") == true ||
                         report.UserVehicleInfo.EngineType?.Contains("BEV") == true ||
                         report.UserVehicleInfo.EngineType?.Contains("Hybrid") == true;
        var evDataFound = extendedResponded > 0 || canResponded > 0;
        checksTable.Add(("EV/Hybrid Data", isLikelyEv ? evDataFound : null,
            isLikelyEv ? (evDataFound ? "EV-specific data found" : "No EV data (may need proprietary protocol)") : "Not an EV"));

        sb.AppendLine("| Check | Status | Details |");
        sb.AppendLine("|-------|--------|---------|");

        foreach (var (check, passed, details) in checksTable)
        {
            var status = passed switch
            {
                true => "?",
                false => "?",
                null => "?"
            };
            sb.AppendLine($"| {check} | {status} | {EscapeMarkdown(details)} |");
        }

        sb.AppendLine();
    }

    private static void AppendSupportedPids(StringBuilder sb, SupportedPidsInfo info)
    {
        sb.AppendLine("## Supported PIDs");
        sb.AppendLine();

        sb.AppendLine($"**Mode 01 (Live Data):** {info.Mode01Pids.Count} PIDs");
        if (info.Mode01Pids.Count > 0)
        {
            sb.AppendLine();
            sb.AppendLine("```");
            sb.AppendLine(string.Join(", ", info.Mode01Pids));
            sb.AppendLine("```");
        }

        sb.AppendLine();
        sb.AppendLine($"**Mode 09 (Vehicle Info):** {info.Mode09Pids.Count} PIDs");
        if (info.Mode09Pids.Count > 0)
        {
            sb.AppendLine();
            sb.AppendLine("```");
            sb.AppendLine(string.Join(", ", info.Mode09Pids));
            sb.AppendLine("```");
        }

        sb.AppendLine();

        if (info.RawResponses.Count > 0)
        {
            sb.AppendLine("<details>");
            sb.AppendLine("<summary>Raw Supported PIDs Responses</summary>");
            sb.AppendLine();
            sb.AppendLine("```");

            foreach (var (query, response) in info.RawResponses)
            {
                sb.AppendLine($"{query}: {response}");
            }

            sb.AppendLine("```");
            sb.AppendLine();
            sb.AppendLine("</details>");
            sb.AppendLine();
        }
    }

    private static void AppendVehicleId(StringBuilder sb, VehicleIdentification info)
    {
        sb.AppendLine("## Vehicle Identification (ECU)");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(info.Vin))
        {
            sb.AppendLine($"**VIN:** `{MaskVin(info.Vin)}` (last 6 masked for privacy)");
        }
        else
        {
            sb.AppendLine("**VIN:** Not available via standard OBD-II");
        }

        if (!string.IsNullOrEmpty(info.CalibrationId))
            sb.AppendLine($"**Calibration ID:** `{EscapeMarkdown(info.CalibrationId.Trim())}`");
        if (!string.IsNullOrEmpty(info.EcuName))
            sb.AppendLine($"**ECU Name:** `{EscapeMarkdown(info.EcuName.Trim())}`");

        sb.AppendLine();

        if (!string.IsNullOrEmpty(info.RawVinResponse))
        {
            sb.AppendLine("<details>");
            sb.AppendLine("<summary>Raw VIN Response</summary>");
            sb.AppendLine();
            sb.AppendLine("```");
            sb.AppendLine(info.RawVinResponse);
            sb.AppendLine("```");
            sb.AppendLine();
            sb.AppendLine("</details>");
            sb.AppendLine();
        }
    }

    private static void AppendVehicleInfo(StringBuilder sb, UserVehicleInfo info)
    {
        sb.AppendLine("## Vehicle Information (User Provided)");
        sb.AppendLine();
        sb.AppendLine("| Property | Value |");
        sb.AppendLine("|----------|-------|");
        sb.AppendLine($"| Year | {info.Year} |");
        sb.AppendLine($"| Make | {info.Make} |");
        sb.AppendLine($"| Model | {info.Model} |");

        if (!string.IsNullOrEmpty(info.Trim))
            sb.AppendLine($"| Trim | {info.Trim} |");
        if (!string.IsNullOrEmpty(info.EngineType))
            sb.AppendLine($"| Engine/Powertrain | {info.EngineType} |");
        if (!string.IsNullOrEmpty(info.TransmissionType))
            sb.AppendLine($"| Transmission | {info.TransmissionType} |");

        sb.AppendLine();

        if (!string.IsNullOrEmpty(info.AdditionalNotes))
        {
            sb.AppendLine("**Additional Notes:**");
            sb.AppendLine($"> {info.AdditionalNotes}");
            sb.AppendLine();
        }
    }

    /// <summary>
    /// Escapes special markdown characters
    /// </summary>
    private static string EscapeMarkdown(string text)
    {
        return text
            .Replace("|", "\\|")
            .Replace("`", "\\`")
            .Replace("\r", "")
            .Replace("\n", " ");
    }

    /// <summary>
    /// Truncates response for table display
    /// </summary>
    private static string TruncateForTable(string? response, int maxLength = 40)
    {
        if (string.IsNullOrEmpty(response))
            return "<empty>";

        var cleaned = response.Replace("\r", "").Replace("\n", " ").Trim();
        if (cleaned.Length <= maxLength)
            return cleaned;

        return cleaned[..(maxLength - 3)] + "...";
    }
}