<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ObdInsight.Tests" />
    <InternalsVisibleTo Include="ObdInsight" />
    <InternalsVisibleTo Include="ObdInsight.IntegrationTests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Serilog" Version="4.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ObdInsight.SourceGeneration\ObdInsight.SourceGeneration.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\ObdInsight.SourceGeneration\ObdInsight.SourceGeneration.csproj" />
  </ItemGroup>

</Project>
