<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TUnit" Version="1.7.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\ObdInsight.Core\ObdInsight.Core.csproj" />
    <ProjectReference Include="..\..\src\ObdInsight.Drivers\ObdInsight.Drivers.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="TestData\*.jsonl" />
  </ItemGroup>

</Project>